### ISSUE TITLE
[BUG] Website link not working

### ISSUE THREAD

**Issue by Pradumnasaraf** [HareerSakhi/HareerSakhi#1]
Hey,
The website link you mentioned in the profile is not reachable

#### Screenshot for refrence
![Screenshot from 2022-08-15 15-02-35](https://user-images.githubusercontent.com/51878265/184612195-116d457d-c935-473b-a9a0-40f220fc536a.png)

**Comment by AvidCoder101** [comment]
@Pradumnasaraf thanks for noticing that! I am currently making it so I will take the link off. Thanks again :)
